"""ARM F report, GENERATED from results/fs/*.json; never edit the output by hand.

    env/bin/python3 ops/fs_report.py   ->  results/fs/ARMF_REPORT.md
"""
import json, pathlib
import numpy as np
ROOT = pathlib.Path(__file__).resolve().parents[1]; R = ROOT / "results" / "fs"
SEGS = ["w00", "ag144", "ag174"]; PRIMARY = "hybrid_3d2d-seed42_step-075000"
A = json.load(open(R / "armf_scores.json")); T = json.load(open(R / "transforms.json"))
P = {s: json.load(open(R / f"profile_{s}.json")) for s in SEGS}
f5 = json.load(open(R / "f5_scores.json")) if (R / "f5_scores.json").exists() else None
Z = json.load(open(ROOT / "results" / "zs" / "armz_scores.json"))["segments"]


def auc(s, c, ck=PRIMARY):
    r = A["segments"][s].get(c, {}).get(ck); return r.get("auc_chosen") if r else None


def f4(x): return "n/a" if x is None else f"{x:.4f}"
def sg(x): return "n/a" if x is None else f"{x:+.4f}"


L = []
L.append("# ARM F: why ink_9um reads the eligible 1.2 m scans worse, and what recovers it\n")
L.append("Generated by `ops/fs_report.py` from `results/fs/*.json`. Pre-registration and its three timestamped"
         " amendments: `results/fs/PREREGISTRATION_ARMF.md` (hashes in `results/fs/prereg.sha256`).\n")
L.append("Model: ink_9um seed42 step-075000 (the primary checkpoint of ARM X to Z), villa's production window,"
         " both depth directions with the label-free choice. Labels: the organisers' 20260918 PHerc0841 labels,"
         " as in ARM Y (2.403 um family) and ARM Z (9.366 um eligible family).\n")
L.append("## Label-free characterisation of the two arrays (no labels, no model)\n")
L.append("| segment | depth offset, median um (p10 to p90) | depth-profile r | adjacent-layer corr, native / 2.403 um |")
L.append("|---|---|---|---|")
for s in SEGS:
    q = P[s]; sh = q["shift_um"]
    L.append(f"| {s} | {sh['median']:+.1f} ({sh['p10']:+.1f} to {sh['p90']:+.1f}) | {sh['median_r']:.3f} | "
             f"{np.mean(q['layer_corr_native']):.3f} / {np.mean(q['layer_corr_pooled']):.3f} |")
p800 = json.load(open(R / "p0800_depth_probe.json")) if (R / "p0800_depth_probe.json").exists() else None
cn = float(np.mean([np.mean(P[s]["layer_corr_native"]) for s in SEGS])); cp = float(np.mean([np.mean(P[s]["layer_corr_pooled"]) for s in SEGS]))
L.append(f"\nMean adjacent-layer correlation: native {cn:.3f}, 2.403 um {cp:.3f}" + (f"; a PHerc0800 8.64 um 116 keV render (the other eligible"
         f" configuration, no labels) {float(np.mean(p800['adjacent_corr'])):.3f}." if p800 else "."))
BC = json.load(open(R / "blur_calibration.json")) if (R / "blur_calibration.json").exists() else None
if BC:
    rng = lambda k: f"{min(v[k] for v in BC.values()):.3f} to {max(v[k] for v in BC.values()):.3f}"
    L.append(f"\nAs a Gaussian (label free, `ops/fs_calib.py`): the eligible input matches the 2.403 um one blurred by sigma {rng('inplane_sigma')} px"
             f" in plane (matched on the fraction of power above 0.6 of Nyquist) and {rng('depth_sigma_after_inplane')} layers in depth after that"
             f" ({rng('depth_sigma_alone')} layers if depth alone is blurred), matched on adjacent-layer correlation. villa's default ink recipe"
             " already draws a per-axis blur sigma from 0.3 to 1.5 for a minority of training patches (the Gaussian blur at probability 0.3"
             " times 0.5 per channel), so the eligible scans sit inside that range but carry it on every input.")
L.append("\nThe native sheet sits within half a 9.366 um layer of the 2.403 um one, so depth placement is not the"
         " difference. The native layers are far more correlated with their neighbours: more depth blur.\n")
L.append("## Conditions, chosen-direction AUC\n")
L.append("| condition | what it is | " + " | ".join(SEGS) + " | median change vs N0 |")
L.append("|---|---|" + "---|" * len(SEGS) + "---|")
DESC = dict(N0="eligible 9.366 um input, unmodified", NS="in-plane sharpening", NH="intensity map only",
            NSH="in-plane sharpening + intensity map (PRIMARY)", NSDH="in-plane + depth sharpening + intensity map",
            NINV="in-plane BLUR (dose control)", ND="depth sharpening only (exploratory)", NDH="depth sharpening + intensity map (exploratory)",
            P0="2.403 um input, production recipe", PDEG="2.403 um blurred in plane to look native", PDEGZ="2.403 um blurred in plane AND depth (exploratory)")
for c in ["N0", "NS", "NH", "NSH", "NSDH", "NINV", "ND", "NDH", "P0", "PDEG", "PDEGZ"]:
    v = [auc(s, c) for s in SEGS]
    if any(x is None for x in v): continue
    base = [auc(s, "P0" if c.startswith("P") else "N0") for s in SEGS]
    ch = "" if c in ("N0", "P0") else sg(float(np.median([a - b for a, b in zip(v, base)])))
    L.append(f"| {c} | {DESC[c]} | " + " | ".join(f4(x) for x in v) + f" | {ch} |")
L.append("\nP conditions are compared with P0, N conditions with N0. Every condition's transform was fitted"
         " WITHOUT labels, on the other two segments' paired arrays (leave one segment out).\n")
F1, F2 = A["F1"], A["F2"]
L.append("## Pre-registered endpoints\n")
per = ", ".join(s + " " + sg(F1["per_segment_gain"][s]) for s in SEGS)
L.append(f"- **F1 (primary), in-plane sharpening + intensity map: median change {sg(F1['median_gain'])}. Verdict: {F1['verdict']}.**"
         f" Per segment {per}.")
L.append(f"- F2 (causal): blurring the 2.403 um input in plane to the native spectrum and mapping its intensities"
         f" costs {F2['median_drop']:.4f} (median), against half the gap {F2['half_gap']:.4f}: {F2['verdict']}.")
dose = ", ".join(sg(A["C_DOSE"]["per_segment"][s]) for s in SEGS)
L.append(f"- C0: N0 and P0 reproduce ARM Z's and ARM Y's stored AUCs exactly: {'PASS' if A['C0']['pass_'] else 'FAIL'}."
         f" C-ID (unit gain reproduces the input byte for byte): {'PASS' if T['C_ID']['pass_'] else 'FAIL'}."
         f" C-DOSE (blurring must not help): {'PASS' if A['C_DOSE']['pass_'] else 'FAIL'},"
         f" changes {dose}.")
gz = [auc(s, "P0") - auc(s, "PDEGZ") for s in SEGS] if all(auc(s, "PDEGZ") is not None for s in SEGS) else None
if gz:
    gzs = ", ".join(f"{x:.4f}" for x in gz)
    L.append(f"- Exploratory: adding DEPTH blur to that degradation (PDEGZ) costs {float(np.median(gz)):.4f} (median;"
             f" {gzs}), {100 * float(np.median(gz)) / F2['median_gap']:.0f}% of the {F2['median_gap']:.4f} gap, against"
             f" {100 * F2['median_drop'] / F2['median_gap']:.0f}% for in-plane blur alone.")
N14 = json.load(open(R / "armf_ndh14.json")) if (R / "armf_ndh14.json").exists() else None
if N14 and N14["summary"]["n_checkpoints"] == 14:
    S = N14["summary"]; dch = sum(v["dir_n0"] != v["dir_ndh"] for r in N14["rows"].values() for v in r.values())
    L.append(f"- Exploratory, all 14 released checkpoints on NDH against the same checkpoints on N0 (ARM Z's rows): **improved in"
             f" {S['pairs_improved']} of {S['pairs']} checkpoint and segment pairs**, median change {sg(S['median_change'])}; the"
             f" label-free direction choice changed in {dch} of {S['pairs']}. The one pair not improved: " + "; ".join(
                 f"{k.replace('hybrid_3d2d-', '')} on {s} ({v['n0']:.4f} to {v['ndh']:.4f})" for k, r in N14["rows"].items() for s, v in r.items() if v["ndh"] <= v["n0"]) + ".")
if f5:
    L.append("\n## Fresh test on a second scroll: PHerc0139 (transforms fitted on PHerc0841 only)\n")
    L.append("| segment | N0 | NDH | NSDH | NSH | ND | 2.403 um P0 |"); L.append("|---|---|---|---|---|---|---|")
    for n, v in f5["auc"].items():
        L.append(f"| {n} | " + " | ".join(f4(v.get(c)) for c in ("N0", "NDH", "NSDH", "NSH", "ND", "P0")) + " |")
    for k, lab in (("F5", "NSH"), ("F5b", "NSDH"), ("F5c", "NDH")):
        if k in f5:
            per = ", ".join(f"{n} {sg(x)}" for n, x in f5[k]["per_segment"].items())
            L.append(f"- {k} ({lab}), per segment {per}; median over w030 and w045: {sg(f5[k]['median_gain'])}, {f5[k]['verdict']}.")
    w43 = f5["auc"].get("w043", {})
    if w43.get("N0") is not None:
        L.append("- w043, descriptive (its 2.399 um render is a training representation): " + ", ".join(
            f"{c} {sg(w43[c] - w43['N0'])}" for c in ("NDH", "ND", "NSDH", "NSH") if w43.get(c) is not None) + ".")
    af = json.load(open(R / "f5_affine.json")) if (R / "f5_affine.json").exists() else None
    if af:
        L.append("- Sensitivity (pre-registered, not an endpoint): labels placed by a per-axis scale and offset fitted to the four quadrant"
                 " alignment peaks instead of one shift: " + ", ".join(f"{k} ({af[k]['condition']}) {sg(af[k]['median_gain'])}" for k in ("F5", "F5b", "F5c")) + ".")
    L.append("\nw030 and w045 are in no ink_9um training representation; w043's 2.399 um render is a training"
             " representation, its native render is not. F5b and F5c share these segments (two tests).")
f6 = json.load(open(R / "f6_scores.json")) if (R / "f6_scores.json").exists() else None
if f6:
    L.append("\n## Fresh test on two scrolls never in training: PHerc0009B (8.64 um, 116 keV) and PHerc0500P2 (9.362 um, 113 keV)\n")
    L.append("| scroll segment | native config | N0 | NDH | ND |"); L.append("|---|---|---|---|---|")
    for n, v in f6["auc"].items():
        m = f6["segments"][n]["meta"]
        L.append(f"| {m['scroll']} {m['seg']} | {m['nat'].split('-volume')[0]} | " + " | ".join(f4(v.get(c)) for c in ("N0", "NDH", "ND")) + " |")
    if "F6" in f6:
        per = ", ".join(f"{n} {sg(x)}" for n, x in f6["F6"]["per_segment"].items())
        L.append(f"- F6 (NDH, the tool as published, with --layer-um at each native spacing): per scroll {per}; mean {sg(f6['F6']['mean_gain'])}, {f6['F6']['verdict']}.")
        nd = {n: v["ND"] - v["N0"] for n, v in f6["auc"].items() if v.get("ND") is not None and v.get("N0") is not None}
        if nd: L.append("- Exploratory, chosen after seeing F6: the depth filter WITHOUT the PHerc0841 intensity map (`--no-map`, ND): per scroll "
                        + ", ".join(f"{n} {sg(x)}" for n, x in nd.items()) + f"; mean {sg(float(np.mean(list(nd.values()))))}.")
    L.append("\nLabels moved onto each native canvas by the voxel ratio and ARM Z's alignment rule: " + "; ".join(
        f"{f6['segments'][n]['meta']['scroll']} shift {f6['segments'][n]['meta']['zalign']['used_offset']} px, peak NCC {f6['segments'][n]['meta']['zalign']['peak_ncc']:.2f}"
        for n in f6["segments"]) + ".")
L.append("\n## Honest limits\n")
L.append("- Labelled segments: three of PHerc0841 (the transforms are fitted on two and tested on the third), three of PHerc0139, one of"
         " PHerc0009B and one of PHerc0500P2. PHerc0009B is the only labelled 8.640 um 116 keV test; every other one is 9.36 um 113 keV.")
L.append("- PHerc0139's native scan supplied 5 of ink_9um's 29 training representations, so it is a weaker fresh test than PHerc0009B and"
         " PHerc0500P2, which are in no training representation.")
L.append("- One checkpoint for every endpoint; the all-checkpoint run is descriptive.")
_ends = [("F5c", f5["F5c"]["median_gain"]) if f5 and "F5c" in f5 else None, ("F6", f6["F6"]["mean_gain"]) if f6 and "F6" in f6 else None]
_ends = [e for e in _ends if e]
L.append("- The depth conditions were promoted after the in-plane primary failed; their fresh confirmatory tests of the published filter (NDH) are "
         + " and ".join(f"{k} {sg(v)}" for k, v in _ends) + ", against a pre-registered bar of +0.020"
         + (" that " + ("both" if len(_ends) == 2 else "it") + " fell short of." if all(0 < v < 0.020 for _, v in _ends) else "."))
(R / "ARMF_REPORT.md").write_text("\n".join(L) + "\n")
print("\n".join(L))
